name: MSBuild with Windows 7 SDK

on:
  push:
    branches:
      - stable-win-7
  pull_request:
    branches:
      - stable-win-7

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install v141_xp toolset
        run: |
          choco install visualstudio2017buildtools --params "--add Microsoft.VisualStudio.Component.VC.v141.xp"
          choco install windows-sdk-7

      - name: Build with Windows 7 SDK
        run: msbuild MirrorHook.sln /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v141_xp

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MirrorHook-artifacts
          path: bin\Release\*.*
